name: Test StackQL Deploy Action

on:
  push:
    paths:
      - '.github/actions/stackql-deploy/action.yml'

jobs:
  stackql-actions-test:
    name: StackQL Actions Test
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run StackQL Deploy Action
        uses: ./.github/actions/stackql-deploy
        with:
          command: 'test'
          stack-dir: 'examples/k8s-the-hard-way'
          stack-env: 'dev'
          env-vars: 'GOOGLE_PROJECT=stackql-k8s-the-hard-way-demo'
